config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users

  resources :users do
    resources :products do
      resources :comments
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments , dependent: :destroy
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :comments
  
  
  after_create :assign_default_role

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def index
 #debugger
 @product = Product.find(params[:product_id])
 @comments = @product.comments.all
end

def new
    #debugger
    @comment = Comment.new
end

def create
    #debugger
    @user = User.find(params[:user_id])
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user_id = current_user.id
    
     @comment.save
    redirect_to user_product_comments_path(current_user,@product)

end


def show
     @comment = Comment.find(params[:id])
end

def destroy
    #debugger
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_product_comments_path(current_user)
end

private
    def comment_params
    	params.require(:comment).permit(:title)
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

def index
    @products = Product.all
end    

def new
    @product = Product.all
end

def create
    #debugger
	@user = User.find(params[:user_id])
	@product = @user.products.create(product_params) 

	if @product.save
      redirect_to  root_path
    else
      render :new
    end
	
end

def show
    #debugger
    #@user = User.find(params[:user_id])
    @products = Product.all
end

def destroy
    #debugger
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to user_product_path(current_user)
end

private
    def product_params
    	params.require(:product).permit(:name, :price)
    end
	


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>Comments Index</h1>

<ul>

  <% @comments.each do |comment| %>

  <li>
    <%= comment.title %>
  </li>
  <%#debugger%>
  <%= link_to "Delete", user_product_comment_path(current_user,comment.product_id,comment.id), method: :delete %>
</ul>

<%end%>
<br><br>

<%= link_to "Back",  new_user_product_comment_path(current_user) %>

app/views/comments/new.html.erb
<h1>Add New Comment</h1>


<%= form_with model: @comment, url: user_product_comments_path do |f| %>

<div>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
</div>
<%#debugger%>
<%#f.hidden_field :user_id, value:  current_user.id %>
<%#f.hidden_field :product_id, value: params[:product_id]%>

<div>
	<%#debugger%>
	<%= f.submit "Submit" %>
	<%= link_to "Show Comments", user_product_comments_path %><br>
	<br>
	<%= link_to "Back", user_products_path(current_user,@comment) %>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task1AgainAddComments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h2>Product Index</h2>

<ul>

  <% @products.each do |product| %>

    <li>
      <%= product.id %>
      <%= product.name %>
      <%= product.price %>
      <%= link_to "comment",new_user_product_comment_path(current_user.id,product.id)%>
     
     <% if current_user.has_role? :seller %>
      <%= link_to "Destroy", user_product_path(current_user.id,product.id), method: :delete, data: { confirm: "Are you sure?" } %>
     <%end%>
     <%end%>
    </li>
    <%= link_to "Back", root_path(@user) %>

app/views/products/new.html.erb
<h1>Add New Product</h1>

<%= form_with model: @product , url: user_products_path, method: :post do |u| %>

<div>
	<%= u.label :name %><br>
	<%= u.text_field :name %>
</div>

<div>
	<%= u.label :price %><br>
	<%= u.text_field :price %>
</div>

<div>
	<%= u.submit "Submit" %>
	<%= link_to "Back", root_path(@product) %>
	<%# debugger %>
</div>


<% end %>

app/views/products/show.html.erb
<h2>Show Products</h2>
<%#debugger%>	

<ul>

  <% @products.each do |product| %>

  <li>
    <%= product.id %>
    <%= product.name %>
    <%= product.price %>
    <%#= render 'comments/form' %>

    <% if current_user.has_role? :seller %>
    <%= link_to "create comment", new_user_product_comment_path(current_user,product.id) %>

    <%= link_to "Destroy", user_product_path(product_id:product.id), method: :delete, data: { confirm: "Are you sure?" } %>
    <%end%>
  </li>

  <% end %>

</ul>
<%= link_to "Back", root_path(@product) %>

app/views/users/index.html.erb
<h1>Users Index</h1>

<% if user_signed_in? %>
  <% if current_user.has_role? :seller %>

    <p> logged in as seller </p> 
    <%= link_to "create product", new_user_product_path(current_user.id) %>&nbsp

  <%# if current_user.has_role? :seller %>
  <%#= button_to "Destroy", user_products_path(current_user, [:products]), method: :delete, data: { confirm: "Are you sure?" } %> 

<% else %>

    <p> signed as buyer </p>

<% end %>
    
    <%= link_to "see all product", user_products_path(current_user.id)%><br><br>
    <%= link_to "Edit", edit_user_registration_path %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>

    <%#debugger%>
    <%#= link_to "Show all Comments", user_product_comments_path(current_user, [:products])  %>

<%else%>

    <%= link_to "Sigup", new_user_registration_path %>
    <%= link_to "Login", user_session_path %>

<%end%>   